default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: gptnme_taskmanager_development

test:
  <<: *default
  database: gptnme_taskmanager_test

production:
  primary: &primary
    url: <%= ENV["DATABASE_URL"] %>
  cable:
    <<: *primary
  queue:
    <<: *primary
  cache:
    <<: *primary